# Site settings
title: "Design Principles"
description: "Design Principles and how to write your own"
twitter: "@dsgnprinciples"
twitter-url: "https://twitter.com/dsgnprinciples"
contribute-url: "https://github.com/benbrignell/design-principles"

url: "https://principles.design"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

collections:
  examples:
      output: true
  tags:
    output: true
    permalink: /category/:name/
